### PR TITLE
The m.wuxiaworld.co class works fine

### PR DESCRIPTION
**Pull request by webdagger**
Hi dr_nyt, 
Great job!
It was easier to read and edit, epub creation was a breeze as well. 
I noticed the novelplanet class has issues running(cfscrape needs to be updated?)
We'll need to disable the button to avoid the user creating another instance. 
I'll edit the run.py file in the Executable Build folder to add m.wuxiaworld.co, I'll also attempt to create a .dmg for mac.
Great job!

### CODE REVIEW

**Comment by dr-nyt** [comment]
There seem to be some conflicting files and I can't seem to officially accept the merge request. Could you try sending the merge request to the beta branch instead?

**Comment by webdagger** [comment]
I will check it out.

**Comment by dr-nyt** [comment]
Oh I just checked the pulse tab in the insight bar of my repository and your commits are registered. I don't why it doesn't show it here though.
https://github.com/dr-nyt/Translated-Novel-Downloader/pulse

I'll send you an invitation to become a direct contributor to this repository. You can choose to accept it or not and further work is not necessary. I appreciate the time you gave to this project :)

Kind Regards,
dr_nyt.

**Comment by webdagger** [comment]
I'm will check it. Thank you for letting me collaborate

**Pull request closed without merging**
